config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "products#index"
  get "stripe/connect", to: "stripe#connect", as: :stripe_connect

  scope '/checkout' do
    post 'create', to: 'stripe#create_checkout', as: 'checkout_create'
    get 'cancel', to: 'stripe#cancel_checkout', as: 'checkout_cancel'
    get 'success', to: 'stripe#success_checkout', as: 'checkout_success'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.seller = current_user
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price)
    end
end

app/controllers/stripe_controller.rb
class StripeController < ApplicationController
    require 'dotenv'
    Dotenv.load('.env')
    
    def connect
      response = HTTParty.post("https://connect.stripe.com/oauth/token",
        query: {
          client_secret: ENV["SECRET_KEY"],
          code: params[:code],
          grant_type: "authorization_code"
        }
      )
  
      if response.parsed_response.key?("error")
        redirect_to edit_user_registration_path,
          notice: response.parsed_response["error_description"]
      else
        stripe_user_id = response.parsed_response["stripe_user_id"]
        current_user.update_attribute(:stripe_user_id, stripe_user_id)
  
        redirect_to root_path,
          notice: 'User successfully connected with Stripe!'
      end
    end
    

    def create_checkout
        @user = current_user
        @product = Product.find(params[:product_id])
        @session = Stripe::Checkout::Session.create({
            line_items: [{
              price_data: {
                currency: 'usd',
                product_data: {
                  name: @product.title,
                },
                unit_amount: (@product.price * 100).to_i,
              },
              quantity: 1,
            }],
            payment_intent_data: {
              application_fee_amount: 123,
              transfer_data: {
                destination: @product.seller.stripe_user_id,
              },
            },
            mode: 'payment',
            success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
            cancel_url: checkout_cancel_url,
          })

        redirect_to @session.url, status:303, allow_other_host: true
      end


    def success_checkout
        @session = Stripe::Checkout::Session.retrieve(params[:session_id])
        @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end

    def cancel_checkout
      puts params
        @session = Stripe::Checkout::Session.retrieve(params[:session_id])
        @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
        def bootstrap_class_for_flash(type)
        case type
          when 'notice' then "alert-info"
          when 'success' then "alert-success"
          when 'error' then "alert-danger"
          when 'alert' then "alert-warning"
        end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/helpers/users_helper.rb
module UsersHelper
  require 'dotenv'
  Dotenv.load('.env')
  

def stripe_button_link
    stripe_url = "https://connect.stripe.com/express/oauth/authorize"
    redirect_uri = stripe_connect_url
    client_id = ENV['CLIENT_ID']
  
    "#{stripe_url}?redirect_uri=#{redirect_uri}&client_id=#{client_id}"
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
      <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingMardi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" <%= link_to 'Home', root_path%></a>
  <a class="navbar-brand"  <%= link_to "Products", products_path %></a>



  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse my-2 my-lg-0" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    <% if user_signed_in? %>
    <li class="nav-item active">
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li class="nav-item active">
    <%= link_to "Account", edit_user_registration_path %>
  </li>

  <% else %>
    <li class="nav-item active m-3">    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li class="nav-item active m-3">
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
  </ul>
  </div>
</nav>
<%= render 'layouts/flash'%>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Back to products", products_path %>
  <%if @product.seller == current_user%>
  <%= link_to "Edit this product", edit_product_path(@product) %> 
  <%= button_to "Destroy this product", @product, method: :delete %>
  <%else%>
    <%= button_to "buy now", checkout_create_path(product_id: @product), class: "btn btn-primary my-3", remote: true%>
  <%end%>
</div>

app/views/stripe/cancel_checkout.html.erb
    <h1>Error during payment!</h1>
    <p>
        Your payment didn't go through
      If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>

app/views/stripe/success_checkout.html.erb
    <h1>Thanks for your order!</h1>
    <p>
      We appreciate your business!
      If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>